Name=zero-lliurex-npu
Name[es]=Instalador de drivers Intel (compute & npu)
Name[ca@valencia]=Instal·lador de drivers Intel (compute & npu)
Name[qcv]=Instal·lador de drivers Intel (compute & npu)
Name[ca_ES]=Instal·lador de drivers Intel (compute & npu)
Comment=Intel driver installer (compute & npu)
Comment[es]=Controladores Intel para GPU & NPU
Comment[ca@valencia]=Controladors Intel per GPU & NPU
Comment[qcv]=Controladors Intel per GPU & NPU
Comment[ca_ES]=Controladors Intel per GPU & NPU
Icon=zero-lliurex-npu
Category=Software
ScriptPath=zero-lliurex-npu.zmd
Groups=sudo;admins;teachers
Using=pkexec
#Service=True
#Modal=True
#Show=False